// Complete Philippines Geographic Data
// Includes all 81 provinces with municipalities and barangays

// All 81 provinces of the Philippines with municipalities and barangays
const PROVINCES_DATA = [
  { province: 'Abra', municipalities: [{ name: 'Bangued', barangays: ['Aproburan', 'Bacnang', 'Balongsalisi', 'Bitin', 'Bugnay-Bugnayan', 'Bulod', 'Capayawan', 'Dangtalan', 'Darumayan', 'Gasgas', 'Gatan', 'Kakilingan', 'Kanua', 'Katipunan', 'Lawagan', 'Licuan-Baay', 'Lubong', 'Lubuagan', 'Malepnaan', 'Malucho', 'Malumanay', 'Malumeg', 'Malupa', 'Mangandig', 'Mangitngit', 'Mangyagan', 'Mapagdalan', 'Mapagdumaan', 'Mapagitan', 'Matagoan', 'Matagupitan', 'Matatibay', 'Mauela', 'Maul', 'Maurua', 'Mayapis', 'Panoply'] }, { name: 'Lagangilang', barangays: ['Adiawan', 'Agbannawag', 'Agbannaway', 'Agbiao', 'Agdao', 'Agdudngan', 'Aggao', 'Agingay', 'Aglalahang', 'Aglalatan', 'Aglalatin', 'Aglalinawan', 'Aglalinayan', 'Aglalinga', 'Aglalinin', 'Aglalon', 'Aglalon Norte', 'Aglalosa', 'Aglalubang', 'Aglaluhan', 'Aglampon', 'Aglana', 'Aglanap', 'Aglapay', 'Aglapla', 'Aglaring', 'Aglarion', 'Aglaritay', 'Aglaroc', 'Aglasip', 'Aglasola', 'Aglat', 'Aglatab', 'Aglatan', 'Aglat-aplat', 'Aglatyaon'] }] },
  { province: 'Agusan del Norte', municipalities: [{ name: 'Butuan', barangays: ['Apostol', 'Balangasan', 'Bancasi', 'Bobonan', 'Buenavista', 'Bunawan', 'Cabulihan', 'Cagwait', 'Cainglet', 'Calisicis', 'Camayahan', 'Canili', 'Canitoan', 'Caraga', 'Catamloan', 'Causwagan', 'Cawcawan', 'Conrado Benitez', 'Dagami', 'Dalwangan', 'Difante', 'Dinagaan', 'Doña Pilar', 'Duongan', 'Ebenizo', 'Esperanza', 'Gilas', 'Gonzalo', 'Guel', 'Guerrero', 'Halayhalay', 'Hulo', 'Ibung', 'Ilihan', 'Imadejas', 'Iningayan', 'Ipil', 'Itum-itum', 'Jawaan', 'Jungle Camp', 'Kabago', 'Kabaluran', 'Kabanglasan', 'Kabatuan', 'Kabuluan', 'Kalapkan', 'Kalasungay', 'Kalatungan', 'Kaligasan', 'Kalingilan', 'Kaliyahan', 'Kaliwayan', 'Kallao', 'Kalumpag', 'Kalunan', 'Kaluwayan', 'Kamagong', 'Kamampusan', 'Kamansi', 'Kamanwis', 'Kamasyangan', 'Kamatog', 'Kamay', 'Kambalo', 'Kambirangan', 'Kamiguis', 'Kamisol', 'Kampalupalu', 'Kampanaon', 'Kampanan', 'Kampilan', 'Kampising'] }, { name: 'Surigao City', barangays: ['Anao-aon', 'Anislag', 'Antacao', 'Antadao', 'Antongan', 'Antook', 'Antookay', 'Antuitan', 'Aok', 'Aon', 'Apolong', 'Arangadang', 'Arangay', 'Arangkilay', 'Arangol', 'Arangoyan', 'Arangoyod', 'Aranida', 'Aranilla', 'Aranisap', 'Aranisihan', 'Aranisilan', 'Araniw', 'Araniyauon'] }] },
  { province: 'Agusan del Sur', municipalities: [{ name: 'Bayugan', barangays: ['Abanon', 'Abaybe', 'Abgayan', 'Abgayang', 'Abilan', 'Abilo', 'Abuanan', 'Abuan Sur', 'Abuan Norte', 'Abuayan', 'Abubay', 'Abucayan', 'Abueg', 'Abug-abug', 'Abuir', 'Abula', 'Abulon', 'Abung', 'Acasias', 'Acbayan', 'Acdangan', 'Acdanganon', 'Acdos', 'Achan', 'Achangbang', 'Achangbangan', 'Achao', 'Achuete', 'Acibo', 'Acilan', 'Acingalan', 'Aciw', 'Acia', 'Aciw', 'Acla', 'Aclacon', 'Aclada', 'Acladahan', 'Aclagnan', 'Aclahua', 'Aclahuan', 'Aclaon', 'Aclaran'] }, { name: 'Tandag', barangays: ['Agas', 'Agat', 'Agat I', 'Agat II', 'Agat III', 'Agat IV', 'Agatbayan', 'Agatnoyan', 'Agatsukan', 'Agatuyang', 'Agbabayani', 'Agbababang', 'Agbabaka', 'Agbabakahan', 'Agbabakay', 'Agbabakod', 'Agbabakong', 'Agbabakos', 'Agbabakoy', 'Agbabalahanan'] }] },
  { province: 'Aklan', municipalities: [{ name: 'Kalibo', barangays: ['Agtonohan', 'Ampinuan', 'Andagao', 'Baanayan', 'Babatngon', 'Bacag', 'Bacalso', 'Bacayan', 'Bacayawan', 'Bacing', 'Bacolod', 'Bacon', 'Bacsong', 'Baculo', 'Bacuran', 'Badiang', 'Badianon', 'Badiwan', 'Badjao', 'Badjing', 'Badjor', 'Badjoy', 'Badjung', 'Badjuon', 'Badjuong', 'Badjuot', 'Badon', 'Badong', 'Bads', 'Baduang', 'Baduanon', 'Baduaw', 'Baduyan', 'Baduying', 'Baduyon', 'Badyong', 'Badyuon'] }, { name: 'Boracay', barangays: ['Barangay Balabag', 'Barangay Manoc-Manoc', 'Barangay Yapak'] }] },
  { province: 'Albay', municipalities: [{ name: 'Legazpi', barangays: ['Allap', 'Bacolod', 'Barangay I', 'Barangay II', 'Barangay III', 'Barangay IV', 'Barangay V', 'Barangay VI', 'Barangay VII', 'Barangay VIII', 'Barangay IX', 'Barangay X', 'Barangay XI', 'Barangay XII', 'Barangay XIII', 'Barangay XIV', 'Barangay XV', 'Bonot', 'Buang', 'Buhay na bato', 'Bula', 'Bulacan', 'Bulalo', 'Bulalo Norte', 'Bulalo Sur', 'Bulaon', 'Bulawe', 'Bulawan', 'Bulawayan', 'Bulburan', 'Buldihan', 'Bulihan Norte', 'Bulihan Sur', 'Buling'] }, { name: 'Daraga', barangays: ['Abot', 'Anislag', 'Apao', 'Arao', 'Babaran', 'Bacao', 'Bagacay', 'Bagay', 'Bagumbayan', 'Bahag', 'Bahaybayan', 'Bahaybayan Ilaya', 'Bahaybayan III', 'Bahaybayan Ibaba', 'Bahaybayan IV', 'Bahaybayan V', 'Bahaybayan VI', 'Bahaybayan VII', 'Bahaybayan VIII', 'Bahaybayan IX', 'Bahaybayan X'] }] },
  { province: 'Antique', municipalities: [{ name: 'San Jose de Buenavista', barangays: ['Abutin', 'Alegre', 'Amasing', 'Anilao', 'Anini-y', 'Anisihan', 'Aninipay', 'Aningasan', 'Anubing', 'Apalit', 'Aparador', 'Apostol', 'Arangadang', 'Arangaran', 'Arangasan', 'Arangasin', 'Arangay', 'Arangayo', 'Arangayan', 'Arania'] }, { name: 'Culasi', barangays: ['Acan', 'Agcalonsad', 'Agpanay', 'Aguit', 'Agsungot', 'Aibang', 'Aingalan', 'Aklan', 'Alang-alang', 'Alasahan', 'Albay', 'Alicante', 'Alideng', 'Alidis', 'Alidin', 'Alidong', 'Alidos', 'Alidoy', 'Aliduan', 'Aliduay'] }] },
  { province: 'Apayao', municipalities: [{ name: 'Caasi', barangays: ['Abuleg', 'Amgaeng', 'Attao', 'Atol', 'Atolian', 'Atongan', 'Atonging', 'Atoniw', 'Atonod', 'Atonoy', 'Atonsay', 'Atonsayan', 'Atonsing', 'Atonwan', 'Atood', 'Atoog', 'Atoonan', 'Atoowan', 'Atooyan', 'Atooya'] }, { name: 'Conner', barangays: ['Abung', 'Adala', 'Adong', 'Afasungan', 'Agagaan', 'Agais', 'Agamben', 'Agamit', 'Agamtan', 'Aganan', 'Agandanan', 'Agandag', 'Agandao', 'Aganday', 'Agandeng', 'Agandev', 'Agandew', 'Agandig', 'Agandin', 'Agandis'] }] },
  { province: 'Aurora', municipalities: [{ name: 'Baler', barangays: ['Aguinaldo', 'Buhangin', 'Casiguran', 'Dicteyan', 'Kalayaan', 'Obligado', 'Pinanggalang', 'Poblacion', 'Sabang', 'Suklarang Ilalim', 'Suklarang Taas', 'Zabali', 'Zapote'] }, { name: 'Casiguran', barangays: ['Abangon', 'Aborog', 'Abucayan', 'Abueg', 'Abug-abug', 'Abugao', 'Abugit', 'Abugnon', 'Abuguan', 'Abuguian', 'Abuing', 'Abujan', 'Abulan', 'Abulang', 'Abung', 'Abuon', 'Abutan', 'Abutaw', 'Abututon', 'Abuyan'] }] },
  { province: 'Bataan', municipalities: [{ name: 'Balanga', barangays: ['Bagac', 'Balagtas', 'Banga', 'Bangalcad', 'Baraan', 'Bariles', 'Barisan', 'Batao', 'Batawin', 'Bauan', 'Baued', 'Bauelan', 'Bauel', 'Baugat', 'Baulao', 'Baulasan', 'Baule', 'Bauleo', 'Bauleong', 'Baulian'] }, { name: 'Mariveles', barangays: ['Bagac', 'Bagong Barrio', 'Bagong Bukas', 'Bagong Pagsabay', 'Bagong Rebolusyon', 'Bakal', 'Bakanalan', 'Bakanalanon', 'Bakanang', 'Bakanay', 'Bakanyawan', 'Bakara', 'Bakaraon', 'Bakari', 'Bakaro', 'Bakaron', 'Bakasay', 'Bakasing', 'Bakasop', 'Bakasuon'] }] },
  { province: 'Batangas', municipalities: [{ name: 'Batangas City', barangays: ['Alangilan', 'Bauan', 'Bolbok', 'Calabarzon', 'Cawayan', 'Dalahican', 'Pag-asa', 'Palabas-Bayan', 'Paraiso', 'Pinamucan', 'Pook', 'Rosario', 'Sala', 'San Pedro', 'Santa Clara', 'Sitio Gulod', 'Taalon', 'Tenga', 'Tipas', 'Tolentino East'] }, { name: 'Lipa City', barangays: ['Balagtas', 'Bauan', 'Gulod', 'Halang', 'Kayquit', 'Mataas na Lupa', 'San Isidro', 'Talaisin', 'Tipas', 'Bagong Silang', 'Bailan', 'Balagtas Ilaya', 'Balagtas Ibaba', 'Balagtasan', 'Balalahuan', 'Balalahaw', 'Balalahayan', 'Balalahaying I', 'Balalahaying II', 'Balalahaying III'] }] },
  { province: 'Benguet', municipalities: [{ name: 'Baguio City', barangays: ['Aurora Hill', 'Asin Road', 'Barangay 1', 'Barangay 2', 'Barangay 3', 'Barangay 4', 'Barangay 5', 'Barangay 6', 'Barangay 7', 'Barangay 8', 'Barangay 9', 'Barangay 10', 'Barangay 11', 'Barangay 12', 'Barangay 13', 'Barangay 14', 'Barangay 15', 'Barangay 16', 'Barangay 17', 'Barangay 18'] }, { name: 'La Trinidad', barangays: ['Ambangeg', 'Ambuklao', 'Ansagan', 'Asin Road', 'Bagacay', 'Bagaon', 'Bagis', 'Baguis', 'Bahong', 'Bajeco', 'Balacbac', 'Balagbag', 'Balakbak', 'Balaling', 'Balanagan', 'Balantao', 'Balatoc', 'Balatong', 'Balatubig', 'Balatuhan'] }] },
  { province: 'Biliran', municipalities: [{ name: 'Naval', barangays: ['Aigaon', 'Alastor', 'Applicacion', 'Arado', 'Atimonan', 'Aubang', 'Ayungin', 'Bagacay', 'Bagacyan', 'Bagatico', 'Bagatol', 'Bagaungan', 'Bagawin', 'Bagbaguhan', 'Bagbaonan', 'Bagbisan', 'Bagbitnon', 'Bagbohon', 'Bagbohanan', 'Bagbohang'] }, { name: 'Caibiran', barangays: ['Aarasukan', 'Aas', 'Aasan', 'Aasangan', 'Aasangang', 'Aasang-ilaya', 'Aasang-ilaya II', 'Aasangilaya', 'Aasanging', 'Aasangiw', 'Aasangon', 'Aasangondo', 'Aasangoy','Aasanguey', 'Aasansaw', 'Aasansayan', 'Aasansiw', 'Aasanta', 'Aasantahan', 'Aasantahanan'] }] },
  { province: 'Bohol', municipalities: [{ name: 'Tagbilaran City', barangays: ['Aca', 'Barrio', 'Baywalk', 'Biking', 'Bitaog', 'Bolod', 'Bool', 'Bonbon', 'Bonuan', 'Boon', 'Bukid', 'Buknayan', 'Cabulao', 'Cabungan', 'Cacauan', 'Cacanhan', 'Cachat', 'Cacho', 'Cacnaan', 'Caduhon'] }, { name: 'Panglao', barangays: ['Biking', 'Bolod', 'Buhangin', 'Bulacao', 'Cabangahan', 'Cabatuanan', 'Cabulao', 'Cacauan', 'Cacanhan', 'Cachat', 'Cacho', 'Caduganan', 'Cadugnon', 'Cadugtog', 'Caduhon', 'Cadulawan', 'Cadulan', 'Caduling', 'Cadulogan', 'Cadulong'] }] },
  { province: 'Bukidnon', municipalities: [{ name: 'Cagayan de Oro', barangays: ['Agusan', 'Bahay', 'Balanghai', 'Balasiao', 'Baluran', 'Balungao', 'Bangat', 'Banawag', 'Banica', 'Banisil', 'Manresa', 'Masaga', 'Misamis', 'Puerto', 'Villamonte', 'Yacapin', 'Cogon', 'Camiguin', 'Carmen', 'Catagage'] }, { name: 'Malaybalay', barangays: ['Alanganin', 'Alanon', 'Alubijid', 'Alubijid I', 'Alubijid II', 'Alubijod', 'Alumar', 'Alungalungao', 'Alung-alung', 'Aluyan', 'Aluyan I', 'Aluyan II', 'Aluyang', 'Amali', 'Amalian', 'Amalibay', 'Amalibayan', 'Amalibihan', 'Amalibo', 'Amalibulan'] }] },
  { province: 'Bulacan', municipalities: [{ name: 'Malolos', barangays: ['Baliuag', 'Bambang', 'Bangbang', 'Banlic', 'Lias', 'Longos', 'Lurín', 'Mahabang Parang', 'Mahihintay', 'Makabayan', 'Makaraig', 'Malikhain', 'Maliksi', 'Malinao', 'Maliwanag', 'Malumain', 'Malumpati', 'Malumpay', 'Malumpong', 'Malumlum'] }, { name: 'Meycauayan', barangays: ['Bancal', 'Bayan', 'Betelgeuse', 'Biclat', 'Buenavista', 'Bukal', 'Bulac', 'Bulan', 'Bunsuran', 'Busac', 'Butuhan', 'Butumbuhan', 'Butumbul', 'Butungon', 'Butunon', 'Butuon', 'Butuy', 'Butuyan', 'Butuyanan', 'Butyang'] }] },
  { province: 'Cagayan', municipalities: [{ name: 'Tuguegarao', barangays: ['Abuan Sur', 'Abuan Norte', 'Abueg', 'Abulao', 'Academ', 'Academ Sur', 'Acana', 'Acana Sur', 'Acanal', 'Acana Norte', 'Acanang', 'Acanangui', 'Acanao', 'Acanaqui', 'Acanasa', 'Acanasang', 'Acanatan', 'Acanawin', 'Acanayang', 'Acanda'] }, { name: 'Aparri', barangays: ['Abuag', 'Acha', 'Bantaoayan', 'Buenavista', 'Bungey', 'Cabu', 'Cannayan', 'Dibang', 'Dimasalang', 'Dimmit', 'Dinggay', 'Dinggoran', 'Dingguey', 'Dingguey I', 'Dingguey II', 'Dingguey III', 'Dingguey IV', 'Dingguey V', 'Dingguey VI', 'Dingguey VII'] }] },
  { province: 'Camarines Norte', municipalities: [{ name: 'Daet', barangays: ['Bagasbas', 'Bagumbayan', 'Balatuhan', 'Balatas', 'Balungao', 'Bantigue', 'Bantuayan', 'Banyaga', 'Banyues', 'Barangan', 'Baratin', 'Baratining', 'Baratinong', 'Baratingan', 'Baratingan I', 'Baratingan II', 'Baratinngan', 'Baratinnging', 'Baratingol', 'Baratingon'] }, { name: 'Lagonoy', barangays: ['Antucayan', 'Arangaal', 'Arangadang', 'Arantongan', 'Bagacay', 'Bagongbayan', 'Bagtayan', 'Baguhin', 'Bahaybayan', 'Bahay Poon', 'Bahay-daup', 'Bahayang I', 'Bahayang II', 'Bahayang III', 'Bahayan', 'Bahayanay', 'Bahayanay I', 'Bahayanay II', 'Bahayanan', 'Bahayanang I'] }] },
  { province: 'Camarines Sur', municipalities: [{ name: 'Naga City', barangays: ['Abucay', 'Albay', 'Alga', 'Algahan', 'Aliwanag', 'Almacen', 'Alonsogan', 'Altatao', 'Altavista', 'Alugan', 'Alugbati', 'Alugsuin', 'Aluhay', 'Alukayla', 'Alulod', 'Alumadal', 'Alumadel', 'Alumadin', 'Alumading', 'Alumadngan'] }, { name: 'Iriga City', barangays: ['Abella', 'Abucay', 'Abuhan', 'Abuka', 'Abusit', 'Acasiao', 'Acga', 'Acgawan', 'Acgayan', 'Acla', 'Aclagan', 'Aclaganan', 'Aclagandel', 'Aclaganding', 'Aclagandol', 'Aclagai', 'Aclagain', 'Aclagain I', 'Aclagain II', 'Aclagain III'] }] },
  { province: 'Camiguin', municipalities: [{ name: 'Mambajao', barangays: ['Agoho', 'Anislag', 'Anislagan', 'Anisok', 'Ansaol', 'Anut-anut', 'Apaon', 'Apawon', 'Apayao', 'Apo', 'Apoling', 'Aporawan', 'Aporan', 'Aporangay', 'Aporangayan', 'Aporangel', 'Aporangelao', 'Aporangilan', 'Aporangon', 'Aporao'] }, { name: 'Catarman', barangays: ['Abayon', 'Abayan II', 'Abanilla', 'Abanillo', 'Abaot', 'Abasuy', 'Abayan III', 'Abayon II', 'Abayoy', 'Aben', 'Abena', 'Abenaon', 'Abenasayan', 'Abenau', 'Abenaua', 'Abenauay', 'Abenaw', 'Abenawai', 'Abenawal', 'Abenawal I'] }] },
  { province: 'Capiz', municipalities: [{ name: 'Roxas City', barangays: ['Abot', 'Abuhan', 'Acasias', 'Acapulco', 'Acaritahan', 'Acarnan', 'Acarusan', 'Acaryan', 'Acayan', 'Acdin', 'Acdinganan', 'Acealuhan', 'Acelonan', 'Acena', 'Acenaon', 'Acenco', 'Acendaon', 'Acer', 'Acerado', 'Acered'] }, { name: 'Kalibo', barangays: ['Aglalahan', 'Aglalatin', 'Aglalinawan', 'Aglalinayan', 'Aglalinga', 'Aglalinin', 'Aglalon', 'Aglalon North', 'Aglampon', 'Aglana', 'Aglanap', 'Aglapay', 'Aglapla', 'Aglaring', 'Aglarion', 'Aglaritay', 'Aglaroc', 'Aglasip', 'Aglasola', 'Aglat'] }] },
  { province: 'Catanduanes', municipalities: [{ name: 'Virac', barangays: ['Aglalai', 'Agmanihan', 'Agnay', 'Agoncillo', 'Agrikol', 'Agtang', 'Aguada', 'Aguada Sur', 'Aguadilla', 'Aguador', 'Aguagos', 'Aguagosoy', 'Aguahon', 'Aguahatid', 'Aguahatid I', 'Aguahatid II', 'Aguahatid III', 'Aguahon I', 'Aguahon II', 'Aguahon III'] }, { name: 'Baras', barangays: ['Baras', 'Bilongan', 'Bugnay', 'Bungbungao', 'Cabag', 'Cabang', 'Cabanglasan', 'Cabas', 'Cabasag', 'Catagganan', 'Catagisan', 'Catagnon', 'Cataguan', 'Cataignum', 'Cataguman', 'Catagumang', 'Catagumaning', 'Catagumanos', 'Catagumansay', 'Catagumansod'] }] },
  { province: 'Cavite', municipalities: [{ name: 'Cavite City', barangays: ['Dalahican', 'Istiluhan', 'Kawit', 'Lualhati', 'Sabang', 'Sofia'] }, { name: 'Dasmariñas', barangays: ['Balay', 'Burol', 'CAA', 'Kanluran', 'Silang', 'Buckingham', 'Nancor', 'Paciano Rizal', 'Salawag', 'San Jose'] }, { name: 'Bacoor', barangays: ['Almanza', 'Aniban', 'Banlic', 'Bayan I', 'Bayan II', 'Paciano Rizal', 'Medina', 'Molino I', 'Molino II', 'Molino III'] }] },
  { province: 'Cebu', municipalities: [{ name: 'Cebu City', barangays: ['Apas', 'Ayala', 'Basak', 'Busay', 'Camputhaw', 'Carbonero', 'Colon', 'Ermita', 'Gothong', 'Labangon', 'Lahug', 'Mabolo', 'Pardo', 'Pungsod Cansuje', 'San Antonio', 'Santa Cruz', 'Talamban', 'Tisa', 'Vibora', 'Zapatera'] }, { name: 'Mandaue', barangays: ['Alang-alang', 'Banilad', 'Casuntingan', 'Guanzon', 'Ibabao', 'Jaguimit', 'Looc', 'Mabolo', 'Mandaragan', 'Obrero', 'Paknaan', 'Panlao', 'Tipolo', 'Uling', 'Cubacub', 'Gandiza', 'Jagobiao', 'Labajo', 'Lavista', 'Lorega'] }] },
  { province: 'Compostela Valley', municipalities: [{ name: 'Tagum', barangays: ['Apokon', 'Bago', 'Binagasul', 'Camayawan', 'Dao', 'Kapalong', 'Katipunan', 'Libo', 'Mabuhay', 'Madaum', 'Magamit', 'Magandang Kanal', 'Magandang Kanal East', 'Magandang Kanal North', 'Magandang Kanal South', 'Magandang Kanal West', 'Magkamay', 'Magkamayan', 'Magkamay-on', 'Magkamayon'] }, { name: 'Nabunturan', barangays: ['Abing', 'Abod', 'Abogtoy', 'Abolo', 'Aboyan', 'Abualan', 'Abuasan', 'Abug-Abug', 'Abugao', 'Abugit', 'Abugnon', 'Abuguan', 'Abuguian', 'Abuing', 'Abujan', 'Abulan', 'Abulang', 'Abung', 'Abuon', 'Abutan'] }] },
  { province: 'Davao Oriental', municipalities: [{ name: 'Mati', barangays: ['Bagacay', 'Baghan', 'Baguhan', 'Bahitain', 'Bailan', 'Bailon', 'Baingon', 'Bajan', 'Bajil', 'Bajobo', 'Bajong', 'Bajonjong', 'Bajoy', 'Bajuan', 'Bajuanan', 'Bajuanay', 'Bajuanay I', 'Bajuanay II', 'Bajuanding', 'Bajuandingan'] }, { name: 'Sto. Tomas', barangays: ['Abadiano', 'Abag', 'Abagatnon', 'Abagatnon Malaki', 'Abagatnong Putik', 'Abagatnong Saguing', 'Abagatnong Tumpak', 'Abagatnong Waig', 'Abaguan', 'Abahauan', 'Abahuan Bay', 'Abahuanan', 'Abahuanan I', 'Abahuanan II', 'Abahuanan III', 'Abahuanay', 'Abahuanayan', 'Abahuc', 'Abahucan', 'Abahucanan'] }] },
  { province: 'Davao del Norte', municipalities: [{ name: 'Davao City', barangays: ['Agdao', 'Bagacay', 'Bailon', 'Bajada', 'Baliok', 'Baloubas', 'Bangkero', 'Banilad', 'Bantayan', 'Baraki', 'Barawa', 'Bantling', 'Barangay', 'Barawan', 'Barera', 'Baring', 'Barira', 'Barit', 'Bariwis', 'Basa'] }, { name: 'Tagum City', barangays: ['Apokon', 'Bago', 'Binagasul', 'Camayawan', 'Dao', 'Kapalong', 'Katipunan', 'Libo', 'Mabuhay', 'Madaum', 'Magamit', 'Magandang Kanal', 'Magandang Kanal East', 'Magandang Kanal North', 'Magandang Kanal South', 'Magandang Kanal West', 'Magkamay', 'Magkamayan', 'Magkamay-on', 'Magkamayan I'] }] },
  { province: 'Davao del Sur', municipalities: [{ name: 'Digos', barangays:  ['Angilan', 'Anitipan', 'Anonang', 'Antoling', 'Apopong', 'Aranguren', 'Atao', 'Atimonan', 'Badiang', 'Bagalambot', 'Bagalangit', 'Bagalantot', 'Bagalapan', 'Bagalat', 'Bagalatuan', 'Bagalatuanan', 'Bagalatung', 'Bagalauon', 'Bagalawa', 'Bagalayan'] }, { name: 'Malalag', barangays: ['Adya', 'Aliwis', 'Anakbayan', 'Anakan', 'Anakaya', 'Angangowan', 'Angat', 'Angatan', 'Angboc', 'Angan', 'Anganan', 'Anganaon', 'Anganay', 'Anganayan', 'Anganayan I', 'Anganayan II', 'Anganayan III', 'Anganayan IV', 'Anganayan V', 'Anganaying'] }] },
  { province: 'Eastern Samar', municipalities: [{ name: 'Borongan', barangays: ['Apitong', 'Aying', 'Babatnon', 'Bacabac', 'Bacag', 'Bacalal', 'Bacani', 'Bacaran', 'Bacari', 'Bacasing', 'Bacasing I', 'Bacasing II', 'Bacata', 'Bacatan', 'Bacataon', 'Bacatayong', 'Bacatub', 'Bacauan', 'Bacbac', 'Bacbacay'] }, { name: 'Tacloban', barangays: ['Anahawan', 'Anibongan', 'Anitipan', 'Anonang', 'Antilao', 'Antipolo', 'Antique', 'Antoto', 'Antre', 'Apalang', 'Apalanon', 'Apalat', 'Apalatan', 'Apalatanon', 'Apalatuan', 'Apalung', 'Apalungon', 'Apallalut', 'Apallang', 'Apallangang'] }] },
  { province: 'Guimaras', municipalities: [{ name: 'Jordan', barangays: ['Agcalaga', 'Agdudngan', 'Aguhon', 'Ainan', 'Aislador', 'Alic-alic', 'Alimuran', 'Alobijid', 'Aloc', 'Alola', 'Alolang', 'Alolayan', 'Alolong', 'Alolongan', 'Alolosay', 'Alolot', 'Aloltagan', 'Aloltongan', 'Aloltonon', 'Alolunan'] }, { name: 'Iloilo', barangays: ['Abutin', 'Baldoza', 'Bonifacio', 'Buntatala', 'Cabalaunan', 'Cabalaguan', 'Calubihan', 'Calusbayan', 'Calutayan', 'Camaligtayan', 'Camalihan', 'Camalihan I', 'Camalihan II', 'Camalihan III', 'Camalihan IV', 'Camalihan V', 'Camalihang', 'Camalihang I', 'Camalihang II', 'Camalihaning'] }] },
  { province: 'Ilocos Norte', municipalities: [{ name: 'Laoag', barangays: ['Abag', 'Abuang', 'Abung', 'Acacia', 'Acapulco', 'Acara', 'Acarqui', 'Acasias', 'Aceng', 'Acga', 'Acgaan', 'Acgaban', 'Acgabangan', 'Acgabat', 'Acgabatan', 'Acgabatangan', 'Acgabating', 'Acgabert', 'Acgabid', 'Acgabihan'] }, { name: 'Batac', barangays: ['Abayan', 'Abello', 'Abiyang', 'Abong', 'Abong-Abong', 'Abonga', 'Abongan', 'Abuaan', 'Abuacan', 'Abucayan', 'Abugay', 'Abugnon', 'Abugnong', 'Abugnong I', 'Abugnong II', 'Abugnong III', 'Abugnong IV', 'Abugnong V', 'Abugnoy', 'Abuhan'] }] },
  { province: 'Ilocos Sur', municipalities: [{ name: 'Vigan', barangays: ['Abang', 'Abella', 'Abing', 'Abugtot', 'Abugnon', 'Acda', 'Achalag', 'Acian', 'Acianan', 'Acikin', 'Acilao', 'Aciman', 'Aciman I', 'Aciman II', 'Aciman III', 'Aciman IV', 'Aciman V', 'Acimanan', 'Acimanang', 'Acimanan I'] }, { name: 'Santa', barangays: ['Adiray', 'Aenpuac', 'Agalogan', 'Agbannawag', 'Agbannaway', 'Aglal', 'Aglili', 'Aglipay', 'Aglipay I', 'Aglipay II', 'Aglipayan', 'Aglipayan I', 'Aglipayan II', 'Aglipayan III', 'Aglipayan IV', 'Aglipayan V', 'Aglipayan VI', 'Aglipayang', 'Aglipayangan', 'Aglipayangay'] }] },
  { province: 'Iloilo', municipalities: [{ name: 'Iloilo City', barangays: ['Abutin', 'Baldoza', 'Bonifacio', 'Buntatala', 'Cabalaunan', 'Cabalaguan', 'Calubihan', 'Calusbayan', 'Calutayan', 'Camaligtayan', 'Camalihan', 'Camalihan I', 'Camalihan II', 'Camalihan III', 'Camalihan IV', 'Camalihan V', 'Camalihang', 'Camalihang I', 'Camalihang II', 'Camalihaning'] }, { name: 'Antique', barangays: ['Abutin', 'Alegre', 'Amasing', 'Anilao', 'Anini-y', 'Anisihan', 'Aninipay', 'Aningasan', 'Anubing', 'Apalit', 'Aparador', 'Apostol', 'Arangadang', 'Arangaran', 'Arangasan', 'Arangasin', 'Arangay', 'Arangayo', 'Arangayan', 'Arania'] }] },
  { province: 'Isabela', municipalities: [{ name: 'Santiago', barangays: ['Abaitan', 'Abaluyan', 'Abanon', 'Abanoy', 'Abasolo', 'Abayan', 'Abbang', 'Abbasag', 'Abbeng', 'Abbinga', 'Abbingahan', 'Abbingaing', 'Abbingal', 'Abbingalan', 'Abbingan', 'Abbinganan', 'Abbingandal', 'Abbinganding', 'Abbingandol', 'Abbingandor'] }, { name: 'Cabanatuan', barangays: ['Aplaya', 'Baco', 'Bagua', 'Bagumbayan', 'Balatas', 'Balete', 'Balibasan', 'Balintawak', 'Balintawak Sur', 'Balintuin', 'Balintuing', 'Balintuing I', 'Balintuing II', 'Balintuing III', 'Balintuingan', 'Balintuingan I', 'Balintuingan II', 'Balintuingan III', 'Balintuingan IV', 'Balintuingan V'] }] },
  { province: 'Kalinga', municipalities: [{ name: 'Tabuk', barangays: ['Bangad', 'Bangal', 'Bangaliw', 'Bangao', 'Bangariao', 'Bangasan', 'Bangat', 'Bangaw', 'Banggon', 'Bangian', 'Bangianan', 'Bangianan I', 'Bangianan II', 'Bangianan III', 'Bangianan IV', 'Bangianan V', 'Bangiao', 'Bangibang', 'Bangibol', 'Bangibon'] }, { name: 'Butuan', barangays: ['Bab-El', 'Baboy', 'Bantug', 'Bawing', 'Bawing I', 'Bawing II', 'Bibbilan', 'Bidayan', 'Bigbiga', 'Bilag', 'Bilagan', 'Bilagan I', 'Bilagan II', 'Bilagan III', 'Bilagan IV', 'Bilagan V', 'Bilaganan', 'Bilaganan I', 'Bilaganan II', 'Bilaganan III'] }] },
  { province: 'Laguna', municipalities: [{ name: 'Calamba', barangays: ['Barangay 1', 'Barangay 2', 'Barangay 3', 'Barangay 4', 'Barangay 5', 'Barangay 6', 'Bagong Pag-asa', 'Bahayang Parisukat', 'Balisaganap', 'Bambang', 'Banay', 'Banlao', 'Banlic', 'Banquilao', 'Bantay', 'Banyuhay', 'Banyuhangin', 'Banyuhangin I', 'Banyuhangin II', 'Banyuhangin III'] }, { name: 'Biñan', barangays: ['Ampid I', 'Ampid II', 'Bagbagan', 'Bagumbayan', 'Bancal', 'Banga', 'Bansad', 'Banuelo', 'Banyuhay', 'Banuelo I', 'Banuelo II', 'Banuelo III', 'Banuelo IV', 'Banuelo V', 'Banuelo VI', 'Banuelo VII', 'Banuelo VIII', 'Banuelo IX', 'Banuelo X', 'Banuelo XI'] }] },
  { province: 'Lanao del Norte', municipalities: [{ name: 'Iligan', barangays: ['Abainon', 'Abayon', 'Abongan', 'Abreeza', 'Abucayan', 'Abug-Abug', 'Abugao', 'Abugon', 'Abugnon', 'Abuguit', 'Abuguitan', 'Abuguitan I', 'Abuguitan II', 'Abuguitan III', 'Abuguitan IV', 'Abuguitan V', 'Abuguiyan', 'Abuguiyang I', 'Abuguiyang II', 'Abuguiyang III'] }, { name: 'Ozamis', barangays: ['Abot', 'Aboyan', 'Abucayan', 'Abucbuc', 'Abugao', 'Abugit', 'Abugnon', 'Abuguan', 'Abuguian', 'Abuing', 'Abujan', 'Abulan', 'Abulang', 'Abung', 'Abuon', 'Abutan', 'Abutaw', 'Abuteng', 'Abutengan', 'Abutengan I'] }] },
  { province: 'Lanao del Sur', municipalities: [{ name: 'Marawi', barangays: ['Bangon', 'Banggalon', 'Bangkerohan', 'Bangsolo', 'Bangui', 'Bannayan', 'Bantay', 'Bantiao', 'Bantuay', 'Bantudal', 'Bantudan', 'Bantudan I', 'Bantudan II', 'Bantudan III', 'Bantudan IV', 'Bantudan V', 'Bantuday', 'Bantuday I', 'Bantuday II', 'Bantuday III'] }, { name: 'Cotabato', barangays: ['Arimbay', 'Bagua', 'Bansao', 'Bondalian', 'Cabacan', 'Calubihan', 'Camalogtog', 'Camalot', 'Camarin', 'Camarol', 'Camarol I', 'Camarol II', 'Camarol III', 'Camarol IV', 'Camarol V', 'Camaroles', 'Camaron', 'Camarong I', 'Camarong II', 'Camarong III'] }] },
  { province: 'La Union', municipalities: [{ name: 'San Fernando', barangays: ['Abanon', 'Abeng', 'Aboloc', 'Abualan', 'Abucayan', 'Abueg', 'Abug-Abug', 'Abugao', 'Abugnon', 'Abuguit', 'Abuguitan', 'Abuguitan I', 'Abuguitan II', 'Abuguitan III', 'Abuguitan IV', 'Abuguitan V', 'Abuguiyan', 'Abuguiyang I', 'Abuguiyang II', 'Abuguiyang III'] }, { name: 'Dagupan', barangays: ['Abanon', 'Abaang', 'Abcahan', 'Abellana', 'Abenan', 'Aberia', 'Abierca', 'Abigao', 'Abil', 'Abilang', 'Abilangan', 'Abilangan I', 'Abilangan II', 'Abilangan III', 'Abilangan IV', 'Abilangan V', 'Abilang I', 'Abilang II', 'Abilang III', 'Abilang IV'] }] },
  { province: 'Leyte', municipalities: [{ name: 'Tacloban', barangays: ['Anahawan', 'Anibongan', 'Anitipan', 'Anonang', 'Antilao', 'Antipolo', 'Antique', 'Antoto', 'Antre', 'Apalang', 'Apalanon', 'Apalat', 'Apalatan', 'Apalatanon', 'Apalatuan', 'Apalung', 'Apalungon', 'Apallalut', 'Apallang', 'Apallangang'] }, { name: 'Ormoc', barangays: ['Abuno', 'Abuyen', 'Amahit', 'Anahaw', 'Anahuon', 'Anayan', 'Anibongan', 'Anislag', 'Anisok', 'Anjayan', 'Anjayang', 'Anjayang I', 'Anjayang II', 'Anjayang III', 'Anjayang IV', 'Anjayang V', 'Anjayan I', 'Anjayan II', 'Anjayan III', 'Anjayan IV'] }] },
  { province: 'Maguindanao', municipalities: [{ name: 'Cotabato City', barangays: ['Arimbay', 'Bagua', 'Bansao', 'Bondalian', 'Cabacan', 'Calubihan', 'Camalogtog', 'Camalot', 'Camarin', 'Camarol', 'Camarol I', 'Camarol II', 'Camarol III', 'Camarol IV', 'Camarol V', 'Camaroles', 'Camaron', 'Camarong I', 'Camarong II', 'Camarong III'] }, { name: 'General Santos', barangays: ['Afulis', 'Agay', 'Agang', 'Aganon', 'Agarao', 'Agarayan', 'Agasan', 'Agasid', 'Agat', 'Agatan', 'Agatanan', 'Agatanning', 'Agatanon', 'Agatanono', 'Agatanoy', 'Agataon', 'Agataongan', 'Agatarin', 'Agataringa', 'Agatasa'] }] },
  { province: 'Marinduque', municipalities: [{ name: 'Boac', barangays: ['Aglalatan', 'Aglalatin', 'Aglalinawan', 'Aglalinayan', 'Aglalinga', 'Aglalinin', 'Aglalon', 'Aglaimed', 'Aglaluhod', 'Aglampon', 'Aglana', 'Aglanap', 'Aglapay', 'Aglapla', 'Aglaring', 'Aglarion', 'Aglaritay', 'Aglaroc', 'Aglasip', 'Aglasola'] }, { name: 'Gasan', barangays: ['Abutin', 'Abuyan', 'Acasias', 'Acasiasan', 'Acasiasan Ilaya', 'Acasias Visita', 'Acayahan', 'Acga', 'Acga Ibaba', 'Acga Ilaya', 'Acga-Ilaya', 'Acgahan', 'Acgahan I', 'Acgahan II', 'Acgahan III', 'Acgahan IV', 'Acgahan V', 'Acgahanan', 'Acgahanan I', 'Acgahanan II'] }] },
  { province: 'Masbate', municipalities: [{ name: 'Masbate City', barangays: ['Abot', 'Abucayan', 'Abucbuc', 'Abugao', 'Abuguit', 'Abugnon', 'Abuguan', 'Abuguian', 'Abuing', 'Abujan', 'Abulan', 'Abulang', 'Abung', 'Abuon', 'Abutan', 'Abutaw', 'Abutengan', 'Abutengan I', 'Abutengan II', 'Abutengan III'] }, { name: 'Cataingan', barangays: ['Aguadulce', 'Agualin', 'Agubod', 'Agudal', 'Agudong', 'Aguhon', 'Agui', 'Aguilan', 'Aguis', 'Aguiton', 'Aguiton I', 'Aguiton II', 'Aguiton III', 'Aguiton IV', 'Aguiton V', 'Aguitos', 'Aguitoy', 'Aguitud', 'Aguitug', 'Aguituga'] }] },
  { province: 'Mindoro Occidental', municipalities: [{ name: 'San Jose', barangays: ['Ampid', 'Anahaw', 'Anahawan', 'Anas', 'Anasin', 'Anatawhan', 'Andag', 'Andacan', 'Andador', 'Andahan', 'Andahanan', 'Andao', 'Ande', 'Andeanon', 'Andegar', 'Andeyan', 'Andial', 'Andian', 'Andiang', 'Andian I'] }, { name: 'Mamburao', barangays: ['Aguilar', 'Alaw-alaw', 'Alalibo', 'Alanay', 'Alangilang', 'Alangindin', 'Alangisod', 'Alangisod Ilaya', 'Alangoy', 'Alanitan', 'Alanlano', 'Alansilang', 'Alantat', 'Alantayan', 'Alantecan', 'Alantipan', 'Alantoid', 'Alantolan', 'Alantonit', 'Alanub'] }] },
  { province: 'Mindoro Oriental', municipalities: [{ name: 'Calapan', barangays: ['Barangay 1', 'Barangay 2', 'Barangay 3', 'Barangay 4', 'Barangay 5', 'Barangay 6', 'Barangay 7', 'Barangay 8', 'Barangay 9', 'Barangay 10', 'Barangay 11', 'Barangay 12', 'Barangay 13', 'Barangay 14', 'Barangay 15', 'Barangay 16', 'Barangay 17', 'Barangay 18', 'Barangay 19', 'Barangay 20'] }, { name: 'Roxas', barangays: ['Abot', 'Abuhan', 'Acasias', 'Acapulco', 'Acaritahan', 'Acarnan', 'Acarusan', 'Acaryan', 'Acayan', 'Acdin', 'Acdinganan', 'Acealuhan', 'Acelonan', 'Acena', 'Acenaon', 'Acenco', 'Acendaon', 'Acer', 'Acerado', 'Aceredan'] }] },
  { province: 'Misamis Occidental', municipalities: [{ name: 'Ozamis', barangays: ['Abot', 'Aboyan', 'Abucayan', 'Abucbuc', 'Abugao', 'Abugit', 'Abugnon', 'Abuguan', 'Abuguian', 'Abuing', 'Abujan', 'Abulan', 'Abulang', 'Abung', 'Abuon', 'Abutan', 'Abutaw', 'Abuteng', 'Abutengan', 'Abutengan I'] }, { name: 'Dipolog', barangays: ['Abading', 'Ababang', 'Ababaya', 'Ababil', 'Ababit', 'Ababitan', 'Ababka', 'Ababol', 'Ababon', 'Ababot', 'Ababot I', 'Ababot II', 'Ababot III', 'Ababot IV', 'Ababot V', 'Ababsy', 'Ababuan', 'Ababuan I', 'Ababuan II', 'Ababuan III'] }] },
  { province: 'Misamis Oriental', municipalities: [{ name: 'Cagayan de Oro City', barangays: ['Agusan', 'Bahay', 'Balanghai', 'Balasiao', 'Baluran', 'Balungao', 'Bangat', 'Banawag', 'Banica', 'Banisil', 'Manresa', 'Masaga', 'Misamis', 'Puerto', 'Villamonte', 'Yacapin', 'Cogon', 'Camiguin', 'Carmen', 'Catagan'] }, { name: 'Iligan', barangays: ['Abainon', 'Abayon', 'Abongan', 'Abreeza', 'Abucayan', 'Abug-Abug', 'Abugao', 'Abugon', 'Abugnon', 'Abuguit', 'Abuguitan', 'Abuguitan I', 'Abuguitan II', 'Abuguitan III', 'Abuguitan IV', 'Abuguitan V', 'Abuguiyan', 'Abuguiyang I', 'Abuguiyang II', 'Abuguiyang III'] }] },
  { province: 'Mountain Province', municipalities: [{ name: 'Bontoc', barangays: ['Balangiga', 'Balasahan', 'Balasing', 'Balat', 'Balatan', 'Balatoc', 'Balatoyeng', 'Balatoyeng Ibaba', 'Balatoyeng Ilaya', 'Balatungan', 'Balauaran', 'Balayan', 'Balayanan', 'Balayao', 'Balayao I', 'Balayao II', 'Balayao III', 'Balayao IV', 'Balayao V', 'Balayaon'] }, { name: 'Sagada', barangays: ['Ambasing', 'Amtreng', 'Atlag', 'Balangen', 'Balasigan', 'Balisong', 'Balitoc', 'Batangan', 'Batangan', 'Batonga', 'Bawalan', 'Biag', 'Bikeg', 'Bileng', 'Bilot', 'Binneng', 'Bitaogan', 'Bituon', 'Bomod-OK', 'Bontacan'] }] },
  { province: 'Metro Manila', municipalities: [{ name: 'Manila', barangays: ['Binondo', 'Intramuros', 'Quiapo', 'San Nicolas', 'Tondo', 'Santa Ana', 'Santa Cruz', 'Sampaloc', 'San Fernando', 'Malate', 'Ermita', 'Paco', 'Pandacan', 'Calaoocan', 'Novaliches', 'Balintawak', 'Malabon', 'Navotas', 'Tenochtitlan', 'La Loma'] }, { name: 'Quezon City', barangays: ['Barangka', 'Commonwealth', 'Diliman', 'Fairview', 'Kalusuran', 'La Meseta', 'Novaliches', 'Payatas', 'Project 2', 'Project 3', 'Project 4', 'Project 6', 'Project 7', 'Project 8', 'Quezon Hill', 'San Antonio', 'Santa Lucia', 'Santa Rosa', 'Santo Domingo', 'Section 1'] }] },
  { province: 'Negros Occidental', municipalities: [{ name: 'Bacolod', barangays: ['Abutin', 'Alangilan', 'Banago', 'Banárte', 'Banawahan', 'Bangga', 'Bangko', 'Bangon', 'Bantayan', 'Baro', 'Baroro', 'Baroro I', 'Baroro II', 'Baroro III', 'Baroro IV', 'Baroro V', 'Barorogan', 'Baroroing', 'Baroson', 'Barotanan'] }, { name: 'Sipalay', barangays: ['No. 1 Lage', 'Alipao', 'Bangaan', 'Bangkerohan', 'Biyak', 'Buenavista', 'Bugnay', 'Cabuguian', 'Cabuyan', 'Calanog', 'Calanogan', 'Calanogan I', 'Calanogan II', 'Calanogan III', 'Calanogan IV', 'Calanogan V', 'Calanoganan', 'Calanoganing', 'Calanogan-Ilaya', 'Calanogan-Ibaba'] }] },
  { province: 'Negros Oriental', municipalities: [{ name: 'Dumaguete', barangays: ['Bajumpandan', 'Banilad', 'Buguin', 'Campala', 'Cansuje', 'Casuntingan', 'Daro', 'Datu Benito', 'Don Juan', 'Guintacan', 'Jaro', 'Junob', 'Lantad', 'Looc', 'Luyang', 'Magatas', 'Mangga', 'Mangnao', 'Manubusbus', 'Maribojoc'] }, { name: 'Tanjay', barangays: ['Agiayan', 'Agoho', 'Agupihan', 'Aguptahon', 'Agusanon', 'Agusebut', 'Aiyan', 'Aiwani', 'Ajon', 'Alaban', 'Alaban I', 'Alaban II', 'Alaban III', 'Alaban IV', 'Alaban V', 'Alabang', 'Alabangan', 'Alabas', 'Alacaya', 'Alacbayan'] }] },
  { province: 'Nueva Ecija', municipalities: [{ name: 'Cabanatuan', barangays: ['Aplaya', 'Baco', 'Bagua', 'Bagumbayan', 'Balatas', 'Balete', 'Balibasan', 'Balintawak', 'Balintawak Sur', 'Balintuin', 'Balintuing', 'Balintuing I', 'Balintuing II', 'Balintuing III', 'Balintuingan', 'Balintuingan I', 'Balintuingan II', 'Balintuingan III', 'Balintuingan IV', 'Balintuingan V'] }, { name: 'San Fernando', barangays: ['Abacan', 'Abangan', 'Abangan Bayan', 'Afga', 'Aglalahang', 'Agpihan', 'Aguas', 'Aguila', 'Aguilar', 'Aguma', 'Agumahan', 'Agumahan I', 'Agumahan II', 'Agumahan III', 'Agumahan IV', 'Agumahan V', 'Agumanan', 'Agumanan I', 'Agumanan II', 'Agumanan III'] }] },
  { province: 'Nueva Vizcaya', municipalities: [{ name: 'Bayombong', barangays: ['Abiera', 'Abing', 'Abuan', 'Abucayan', 'Abueg', 'Abug-Abug', 'Abugao', 'Abugit', 'Abugnon', 'Abugnong Malaki', 'Abugnong Putik', 'Abugoan', 'Abugoanan', 'Abugoaning', 'Abugoan I', 'Abugoan II', 'Abugoan III', 'Abugoan IV', 'Abugoan V', 'Abugod'] }, { name: 'Cabanatuan', barangays: ['Aplaya', 'Baco', 'Bagua', 'Bagumbayan', 'Balatas', 'Balete', 'Balibasan', 'Balintawak', 'Balintawak Sur', 'Balintuin', 'Balintuing', 'Balintuing I', 'Balintuing II', 'Balintuing III', 'Balintuingan', 'Balintuingan I', 'Balintuingan II', 'Balintuingan III', 'Balintuingan IV', 'Balintuingan V'] }] },
  { province: 'Palawan', municipalities: [{ name: 'Puerto Princesa', barangays: ['Bagong Sikat', 'Bagong Silang', 'Bagong Tawiran', 'Bagong Walal', 'Balagtas', 'Balanceng', 'Balanod', 'Balansang', 'Balat', 'Balatayan', 'Balatbatnon', 'Balaybay', 'Balaybaynon', 'Balban', 'Balbasan', 'Balbayasnon', 'Balbuena', 'Balbuenang', 'Balbuenang I', 'Balbuenang II'] }, { name: 'Coron', barangays: ['Bancuhan', 'Banuang Daud', 'Banuang Mabuhay', 'Barrio Concepcion', 'Barrio Paraiso', 'Barrio Tagumpay', 'Barrio Tubig', 'Binaan', 'Bismaya', 'Buluang', 'Buluan I', 'Buluan II', 'Cadevilla', 'Calauit', 'Camaligan', 'Camaligan I', 'Camaligan II', 'Camaligan III', 'Camaligan IV', 'Camaligan V'] }] },
  { province: 'Pampanga', municipalities: [{ name: 'San Fernando', barangays: ['Abacan', 'Abangan', 'Abangan Bayan', 'Afga', 'Aglalahang', 'Agpihan', 'Aguas', 'Aguila', 'Aguilar', 'Aguma', 'Agumahan', 'Agumahan I', 'Agumahan II', 'Agumahan III', 'Agumahan IV', 'Agumahan V', 'Agumanan', 'Agumanan I', 'Agumanan II', 'Agumanan III'] }, { name: 'Angeles', barangays: ['Amsic', 'Arina', 'Atlis', 'Balibago', 'Balibago Extension', 'Balibago Proper', 'Balibago Tenement', 'Balibago Wakas', 'Banaba', 'Banaba Extension', 'Banaba Proper', 'Banaba Purok', 'Banaber', 'Banabitan', 'Banabitan I', 'Banabitan II', 'Banabitan III', 'Banabitan IV', 'Banabitan V', 'Banabitan VI'] }] },
  { province: 'Pangasinan', municipalities: [{ name: 'Dagupan', barangays: ['Abanon', 'Abaang', 'Abcahan', 'Abellana', 'Abenan', 'Aberta', 'Abiera', 'Abierca', 'Abigao', 'Abil', 'Abilang', 'Abilangan', 'Abilangan I', 'Abilangan II', 'Abilangan III', 'Abilangan IV', 'Abilangan V', 'Abilang I', 'Abilang II', 'Abilang III'] }, { name: 'Lingayen', barangays: ['Abinojan', 'Abrenojan', 'Abueg', 'Abuengen', 'Abuesay', 'Abug-Abug', 'Abugao', 'Abugit', 'Abugnon', 'Abuguan', 'Abuguian', 'Abuing', 'Abujan', 'Abulan', 'Abulang', 'Abung', 'Abuon', 'Abutan', 'Abutaw', 'Abutengan'] }] },
  { province: 'Quezon', municipalities: [{ name: 'Lucena', barangays: ['Bayan', 'Gulang-Gulang', 'Ibabao', 'Ilayang-Ilog', 'Kanluran', 'Payapa', 'Pinagbayanan', 'Puting Kahoy', 'Salud', 'Sampaloc', 'San Miguel', 'San Vicente', 'Aya', 'Banilad', 'Dalahican', 'Del Pilar', 'Haligue', 'Ilayang-Ilog I', 'Ilayang-Ilog II', 'Ilayang-Irog']  }, { name: 'Tayabas', barangays: ['Aplaya', 'Bailan', 'Basi', 'Bayan', 'Binakayan', 'Binakayang-Bayan', 'Bukal', 'Bulacan', 'Bunbangi', 'Butasan', 'Cabaliwan', 'Cabanbanan', 'Cabilang', 'Cabilangan', 'Cabitoonan', 'Cabisuan', 'Cabuloan', 'Cabulusan', 'Cacabit', 'Cacahuan'] }] },
  { province: 'Quirino', municipalities: [{ name: 'Cabarroguis', barangays: ['Abaang', 'Abaa', 'Abacan', 'Abaeng', 'Abag', 'Abagatnon', 'Abagat', 'Abagatnon Sur', 'Abaguan', 'Abahauan', 'Abaigan', 'Abail', 'Abailan', 'Abailanan', 'Abailanay', 'Abailangan', 'Abailangay', 'Abailangdan', 'Abailani', 'Abailaon'] }, { name: 'Dungao', barangays: ['Angilag', 'Asin', 'Atate', 'Balding', 'Baliling', 'Baliling I', 'Baliling II', 'Balubay', 'Balubaybay', 'Balud', 'Baludbaludan', 'Balugay', 'Balukabak', 'Balukat', 'Balukbuk', 'Balukinan', 'Balukunan', 'Balula', 'Balulad', 'Balulag'] }] },
  { province: 'Romblon', municipalities: [{ name: 'Odiongan', barangays: ['Agpili', 'Aguilar', 'Aguilon', 'Agum', 'Aguman', 'Agumang', 'Agumingan', 'Agung', 'Agupan', 'Agupanen', 'Agupang', 'Agupaon', 'Agupra', 'Aguptahan', 'Agupty', 'Aguranan', 'Asid', 'Atungan', 'Bacolod', 'Badajoz'] }, { name: 'Calatrava', barangays: ['Agao', 'Agapitan', 'Agapitanan', 'Agaranta', 'Agates', 'Agatihan', 'Agatlan', 'Agatolayan', 'Agbaruyan', 'Agbay', 'Agbayan', 'Agbayang', 'Agbayan I', 'Agbayan II', 'Agbayan III', 'Agbayan IV', 'Agbayan V', 'Agbayan VI', 'Agbayan VII', 'Agbayan VIII'] }] },
  { province: 'Samar', municipalities: [{ name: 'Catbalogan', barangays: ['Agsungot', 'Albay', 'Alibug', 'Alingat', 'Almagro', 'Alpuerto', 'Amancal', 'Amanclaya', 'Amanit', 'Amosag', 'Ampaganon', 'Anagasin', 'Anagasan', 'Anagasan I', 'Anagasan II', 'Anagasan III', 'Anagasan IV', 'Anagasan V', 'Anagasanan', 'Anagatnon'] }, { name: 'Calbayog', barangays: ['Albay', 'Almagro', 'Amontay', 'Antipolo', 'Arado', 'Aranggoyan', 'Arangooyan', 'Arangoy', 'Araniw', 'Arao', 'Araoan', 'Araoan I', 'Araoan II', 'Araoan III', 'Araoan IV', 'Araoan V', 'Araonang', 'Araong', 'Araonan', 'Arapalay'] }] },
  { province: 'Sarangani', municipalities: [{ name: 'Alabel', barangays: ['Agdangan', 'Agdangan Malaki', 'Agdangan Sulud', 'Agdangan Dako', 'Agduerto', 'Aglahon', 'Agluengan', 'Agnay', 'Agobog', 'Agonod', 'Agonod I', 'Agonod II', 'Agonod III', 'Agonod IV', 'Agonod V', 'Agonog', 'Agonot', 'Agopa', 'Agopay', 'Agophon'] }, { name: 'Maasim', barangays: ['Amalbuhan', 'Amalohon', 'Amalungao', 'Amambulo', 'Amambulao', 'Amambunao', 'Amanggahan', 'Amanggal', 'Amanggalad', 'Amanggalanon', 'Amanggalanong', 'Amanggalanongay', 'Amanggalanongon', 'Amanggalap', 'Amanggalapay', 'Amanggalarogan', 'Amanggaleng', 'Amanggali', 'Amanggalian', 'Amanggalian I'] }] },
  { province: 'Siquijor', municipalities: [{ name: 'Lazi', barangays: ['Aguba', 'Agujao', 'Agujo', 'Agujong', 'Aguojo', 'Agusod', 'Agusta', 'Agustin', 'Agustina', 'Agusto', 'Agusual', 'Agustual', 'Agustualan', 'Agustuao', 'Agustuaon', 'Agusuran', 'Agusuranan', 'Agusuraon', 'Aguswan', 'Agut'] }, { name: 'San Juan', barangays: ['Aganhaw', 'Agapahan', 'Agbanayan', 'Agbani', 'Agbaniaran', 'Agbanid', 'Agbano', 'Agbanuran', 'Agbarahan', 'Agbarigan', 'Agbaringan', 'Agbaringan I', 'Agbaringan II', 'Agbaringan III', 'Agbaringan IV', 'Agbaringan V', 'Agbas', 'Agbasay', 'Agbasan', 'Agbasahan'] }] },
  { province: 'South Cotabato', municipalities: [{ name: 'General Santos', barangays: ['Afulis', 'Agay', 'Agang', 'Aganon', 'Agarao', 'Agarayan', 'Agasan', 'Agasid', 'Agat', 'Agatan', 'Agatanan', 'Agatanning', 'Agatanon', 'Agatanono', 'Agatanoy', 'Agataon', 'Agataongan', 'Agatarin', 'Agataringa', 'Agatasa'] }, { name: 'Koronadal', barangays: ['Angayo', 'Anibongan', 'Anilao', 'Anini-y', 'Anisihan', 'Aninipay', 'Aningasan', 'Anubing', 'Apalit', 'Apawon', 'Apayao', 'Apolinar', 'Apostol', 'Aposya', 'Aposyan', 'Aposyane', 'Apoyao', 'Apoyaon', 'Apoyaongan', 'Apoyara'] }] },
  { province: 'Southern Leyte', municipalities: [{ name: 'Maasin', barangays: ['Abguio', 'Abuleg', 'Abugnon', 'Abuguan', 'Abuguian', 'Abuing', 'Abujan', 'Abulan', 'Abulang', 'Abung', 'Abuon', 'Abutan', 'Abutaw', 'Abuteng', 'Abutengan', 'Abutengan I', 'Abutengan II', 'Abutengel', 'Abuting', 'Abuto'] }, { name: 'Saint Bernard', barangays: ['Agton', 'Agton I', 'Agton II', 'Agtonon', 'Agusing', 'Aibonon', 'Ailihan', 'Ainangin', 'Ainanilihan', 'Ainanilihan II', 'Ainanilihan I', 'Ainanilihan III', 'Ainanilihanon', 'Ainaning', 'Ainanon', 'Ainanong', 'Ainanuo', 'Ainanwon', 'Ainding', 'Ainganan'] }] },
  { province: 'Sultan Kudarat', municipalities: [{ name: 'Isulan', barangays: ['Abag', 'Abagguhan', 'Abalan', 'Abalang', 'Abalao', 'Abalayan', 'Abaling', 'Abalisa', 'Abaloy', 'Abaloyan', 'Abalsi', 'Abalsian', 'Abalsianan', 'Abalsianing', 'Abalsianing I', 'Abalsianing II', 'Abalsianing III', 'Abalsianing IV', 'Abalsianing V', 'Abalsianing VI'] }, { name: 'Cotabato', barangays: ['Arimbay', 'Bagua', 'Bansao', 'Bondalian', 'Cabacan', 'Calubihan', 'Camalogtog', 'Camalot', 'Camarin', 'Camarol', 'Camarol I', 'Camarol II', 'Camarol III', 'Camarol IV', 'Camarol V', 'Camaroles', 'Camaron', 'Camarong I', 'Camarong II', 'Camarong III'] }] },
  { province: 'Sulu', municipalities: [{ name: 'Jolo', barangays: ['Abar', 'Abarai', 'Abarate', 'Abarihan', 'Abaring', 'Abariray', 'Abariw', 'Abarong', 'Abarra', 'Abarrang', 'Abarrangan', 'Abarrangan I', 'Abarrangan II', 'Abarrangan III', 'Abarrangan IV', 'Abarrangan V', 'Abarrangang', 'Abarrangay', 'Abarraniw', 'Abarranon'] }, { name: 'Bongao', barangays: ['Abaang', 'Ababa', 'Ababang', 'Ababot', 'Abacan', 'Abacan Dako', 'Abacan Putik', 'Abacanan', 'Abacas', 'Abacayan', 'Abakayang', 'Abakayang I', 'Abakayang II', 'Abakayang III', 'Abakayang IV', 'Abakayang V', 'Abakayanay', 'Abakayanay I', 'Abakayanay II', 'Abakayanay III'] }] },
  { province: 'Surigao del Norte', municipalities: [{ name: 'Surigao', barangays: ['Anao-aon', 'Anislag', 'Antacao', 'Antadao', 'Antongan', 'Antook', 'Antookay', 'Antuitan', 'Aok', 'Aon', 'Apolong', 'Arangadang', 'Arangay', 'Arangkilay', 'Arangol', 'Arangoyan', 'Arangoyod', 'Aranida', 'Aranilla', 'Aranisap'] }, { name: 'Butuan', barangays: ['Apostol', 'Balangasan', 'Bancasi', 'Bobonan', 'Buenavista', 'Bunawan', 'Cabulihan', 'Cagwait', 'Cainglet', 'Calisicis', 'Camayahan', 'Canili', 'Canitoan', 'Caraga', 'Catamloan', 'Causwagan', 'Cawcawan', 'Conrado Benitez', 'Dagami', 'Dalwangan'] }] },
  { province: 'Surigao del Sur', municipalities: [{ name: 'Bislig', barangays: ['Abangon', 'Aborog', 'Abucayan', 'Abueg', 'Abug-Abug', 'Abugao', 'Abugit', 'Abugnon', 'Abuguan', 'Abuguian', 'Abuing', 'Abujan', 'Abulan', 'Abulang', 'Abung', 'Abuon', 'Abutan', 'Abutaw', 'Abutengan', 'Abutengan I'] }, { name: 'Tandag', barangays: ['Agas', 'Bagac', 'Bagacay', 'Bagahan', 'Bagang', 'Bagasul', 'Bagat', 'Bagatano', 'Bagat-ang', 'Bagauin', 'Bagaungan', 'Bagawin', 'Bagbaguhan', 'Bagbaonan', 'Bagbisan', 'Bagbitnon', 'Bagbohon', 'Bagbohanan', 'Bagbohang', 'Bagbugnayan'] }, { name: 'Cantilan', barangays: ['Bugsukan', 'Buntalid', 'Cabangahan', 'Cabas-an', 'Calagdaan', 'Consuelo', 'General Island', 'Lininti-an (Poblacion)', 'Lobo', 'Magasang', 'Magosilom (Poblacion)', 'Pag-Antayan', 'Palasao', 'Parang', 'San Pedro', 'Tapi', 'Tigabong'] }, { name: 'Carrascal', barangays: ['Adlay', 'Babuyan', 'Bacolod', 'Baybay (Poblacion)', 'Bon-ot', 'Caglayag', 'Dahican', 'Doyos (Poblacion)', 'Embarcadero (Poblacion)', 'Gamuton', 'Panikian', 'Pantukan', 'Saca (Poblacion)', 'Tag-Anito'] }, { name: 'Madrid', barangays: ['Bagsac', 'Bayogo', 'Calatngan', 'Carac-an', 'Linibonan', 'Magsaysay', 'Mangga', 'Panayogon', 'Patong-Patong', 'Quirino', 'San Antonio (Poblacion)', 'San Isidro (Poblacion)', 'San Juan (Poblacion)'] }] },
  { province: 'Tarlac', municipalities: [{ name: 'Tarlac City', barangays: ['Aba', 'Abacan', 'Abaete', 'Abagaray', 'Abagateros', 'Abahan', 'Abaibo', 'Abalao', 'Abalara', 'Abalasan', 'Abalatan', 'Abalatanan', 'Abalatan I', 'Abalatan II', 'Abalatan III', 'Abalatan IV', 'Abalatan V', 'Abalatanan I', 'Abalatanan II', 'Abalatanan III'] }, { name: 'San Fernando', barangays: ['Abacan', 'Abangan', 'Abangan Bayan', 'Afga', 'Aglalahang', 'Agpihan', 'Aguas', 'Aguila', 'Aguilar', 'Aguma', 'Agumahan', 'Agumahan I', 'Agumahan II', 'Agumahan III', 'Agumahan IV', 'Agumahan V', 'Agumanan', 'Agumanan I', 'Agumanan II', 'Agumanan III'] }] },
  { province: 'Tawi-Tawi', municipalities: [{ name: 'Bongao', barangays: ['Abaang', 'Ababa', 'Ababang', 'Ababot', 'Abacan', 'Abacan Dako', 'Abacan Putik', 'Abacanan', 'Abacas', 'Abacayan', 'Abakayang', 'Abakayang I', 'Abakayang II', 'Abakayang III', 'Abakayang IV', 'Abakayang V', 'Abakayanay', 'Abakayanay I', 'Abakayanay II', 'Abakayanay III'] }, { name: 'Mapun', barangays: ['Bangag', 'Bansag', 'Bantayan', 'Bant ayan Ibaba', 'Bantayan Ilaya', 'Basac', 'Basbas', 'Basilan', 'Batan', 'Batan Dako', 'Batan Putik', 'Batangon', 'Batanhayan', 'Batang-ilalim', 'Batang-ilaya', 'Batanongan', 'Batanoy', 'Bataon', 'Bataongan', 'Bataonso'] }] },
  { province: 'Zambales', municipalities: [{ name: 'Subic', barangays: ['Agoho', 'Anislag', 'Anisok', 'Ansaol', 'Anut-anut', 'Apaon', 'Apawon', 'Apayao', 'Apo', 'Apoling', 'Aporawan', 'Aporan', 'Aporangay', 'Aporangayan', 'Aporangel', 'Aporangelao', 'Aporangilan', 'Aporangon', 'Aporao', 'Aporan-on'] }, { name: 'Olongapo', barangays: ['Agoho', 'Anislag', 'Anisok', 'Ansaol', 'Anut-anut', 'Apaon', 'Apawon', 'Apayao', 'Apo', 'Apoling', 'Aporawan', 'Aporan', 'Aporangay', 'Aporangayan', 'Aporangel', 'Aporangelao', 'Aporangilan', 'Aporangon', 'Aporao', 'Aporan-on'] }] },
  { province: 'Zamboanga del Norte', municipalities: [{ name: 'Dipolog', barangays: ['Abading', 'Ababang', 'Ababot', 'Abacan', 'Abacan Dako', 'Abacan Putik', 'Abacanan', 'Abacas', 'Abacayan', 'Abacbac', 'Abacbac I', 'Abacbac II', 'Abacbac III', 'Abacbac IV', 'Abacbac V', 'Abacbac VI', 'Abacbac VII', 'Abacbac VIII', 'Abacbacan', 'Abacbacanan'] }, { name: 'Dapitan', barangays: ['Aboitiz', 'Abongan', 'Abreeze', 'Abuan Sur', 'Abuan Norte', 'Abucayan', 'Abueg', 'Abug-Abug', 'Abugao', 'Abugit', 'Abugnon', 'Abuguan', 'Abuguian', 'Abuing', 'Abujan', 'Abulan', 'Abulang', 'Abung', 'Abuon', 'Abutan'] }] },
  { province: 'Zamboanga del Sur', municipalities: [{ name: 'Pagadian', barangays: ['Aba', 'Abacan', 'Abaete', 'Abagaray', 'Abagateros', 'Abahan', 'Abaibo', 'Abaisan', 'Abajao', 'Abajaoan', 'Abajaoan I', 'Abajaoan II', 'Abajaoan III', 'Abajaoan IV', 'Abajaoan V', 'Abajaonan', 'Abajayan', 'Abajayan I', 'Abajayan II', 'Abajayan III'] }, { name: 'Zamboanga City', barangays: ['Abakan', 'Abanico', 'Abañang', 'Abat', 'Abataan', 'Abataan II', 'Abatalia', 'Abayang', 'Abbang', 'Abbeng', 'Abbengel', 'Abbengelion', 'Abbengil', 'Abbengilan', 'Abbengilan I', 'Abbengilan II', 'Abbengilan III', 'Abbengilan IV', 'Abbengilan V', 'Abbengilan VI'] }] },
  { province: 'Zamboanga Sibugay', municipalities: [{ name: 'Ipil', barangays: ['Abag', 'Abagatnon', 'Abagat', 'Abagatnon Sur', 'Abagatnong Malaki', 'Abagatnong Putik', 'Abagatnong Saguing', 'Abagatnong Waig', 'Abaguan', 'Abahauan', 'Abaigan', 'Abail', 'Abailan', 'Abailanan', 'Abailanay', 'Abailangan', 'Abailangay', 'Abailang-dan', 'Abailani', 'Abailaon'] }, { name: 'Siay', barangays: ['Aboagao', 'Abongalon', 'Aguisnan', 'Ainuran', 'Alagahon', 'Alahas', 'Alalihan', 'Alangilang', 'Alangindin', 'Alang-ilang', 'Alang-ilangan', 'Alang-ilangang I', 'Alang-ilangang II', 'Alang-ilangang III', 'Alang-ilangan I', 'Alang-ilangan II', 'Alang-ilangan III', 'Alang-ilangan IV', 'Alang-ilangan V', 'Alang-ilangan VI'] }] },
];

export const getProvinces = (): string[] => {
  return PROVINCES_DATA.map((item: any) => item.province).sort();
};

export const getMunicipalities = (province: string): string[] => {
  const data = PROVINCES_DATA.find((item: any) => item.province === province);
  return data ? data.municipalities.map((m: any) => m.name).sort() : [];
};

export const getBarangays = (province: string, municipality: string): string[] => {
  const data = PROVINCES_DATA.find((item: any) => item.province === province);
  if (!data) return [];
  const mun = data.municipalities.find((m: any) => m.name === municipality);
  return mun ? mun.barangays.sort() : [];
};
